apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-claim
  labels:
    app: db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi