FROM golang:alpine

# Install git
RUN apk update && apk add --no-cache git

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download 

# Copy the source from the current directory to the working Directory inside the container 
COPY . .

# Run tests (NOTE: need to run each test directory separately or there will be race conditions when accessing the DB)
CMD CGO_ENABLED=0 go test -v  ./tests/controllertests
CMD CGO_ENABLED=0 go test -v  ./tests/modeltests