version: '3'

services:
  app_test:
    container_name: blog_api_test
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
    - blog_api_test:/app/src/app/
    depends_on:
      - db_test
    links:
      - db_test

  db_test:
    image: postgres:latest
    container_name: blog_db_test
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
    restart: on-failure
    ports:
    - '5555:5432'
    volumes:
    - db_postgres_test:/var/lib/postgresql/data

volumes:
  blog_api_test:
  db_postgres_test: